### ISSUE TITLE
'f2p_lvl3' is not a valid PlayerBuild variant.

### ISSUE THREAD

**Issue by ciaransanders** [Jonxslays/wom.py#28]
A ValueError is thrown when trying to run `await client.groups.get_details(44)`

It seems to be that the `PlayerBuild` enum class is missing an entry for f2p lvl3 account builds. Adding `f2p_lvl3 = "f2p_lvl3"` fixes the ValueError.

**Comment by Jonxslays** [comment]
Hi, thanks for the report. This was recently added by WOM, and released last month in [v0.6.1](https://github.com/Jonxslays/wom.py/releases/tag/v0.6.1).

I'd recommend updating to that version. If you run into other related issues feel free to let me know.

**Comment by ciaransanders** [comment]
Ah I'm sorry about that, I genuinely thought I had upgraded to the newest version of WOM when investigating this issue.

**Comment by Jonxslays** [comment]
No worries! Happens to everyone.

I did just run a `get_details` on that group id: 44. I got another error unrelated to the `F2pLvl3` player build. I'm investigating that - just in case you run into it yourself. It looks like the API is returning bad data, a player who has no `updated_at` property, which should never be the case in my experience. I'll give an update here and open a proper issue if it's anything that needs to be fixed on my side.

**Comment by ciaransanders** [comment]
Thank you for the help! Yes I was just running into that error now and was also investigating the cause of it :smile: Not sure how their account ended up in that state on WOM either, I'd be curious to find out since the official hiscores says they do not exist

**Comment by Jonxslays** [comment]
Yeah, the WOM docs list a players updated at as not nullable, but it can be if they never had a successful update.

I will be cutting a release tonight with a fix for this along with helpful logging if this type of thing occurs in the future. Thanks a lot for bringing this to my attention.

Tracking issue: #29

**Comment by Jonxslays** [comment]
Ok, @CiaranSanders, this is fixed in [v0.7.0](https://github.com/Jonxslays/wom.py/releases/tag/v0.7.0).

Hit that `pip install -U wom.py` button one more time and you should be good to go!

Thanks again for the report.
