### ISSUE TITLE
New metric enum (Random)

### ISSUE THREAD

**Issue by OttoGrotto** [Jonxslays/wom.py#41]
As the title says, add a Random enum for a random skill to be chosen from the existing enums

I cloned the repo to my personal machine and tried playing around with adding a "random" enum with a custom, while I couldn't make the enum pick a random skill from inside the lib, making a custom handler for it shouldn't be that hard when calling it in your personal projects, looking into making it lib based could be really nice to have as an option (Atleast for me when working on a discord bot with select menus having the option to let the bot pick a random skill is convenient)

**Comment by OttoGrotto** [comment]
I can't seem to add the enhancement label, if someone could help me with it

**Comment by Jonxslays** [comment]
Hi, thanks for the suggestion.

While I don't think adding a new enum is the right solution here, I do think adding a method that chooses randomly for you could work. 

I will investigate this.

**Comment by Jonxslays** [comment]
Hey @OttoGrotto,

This is now implemented on the master branch. I probably won't be cutting a release for a week or two but you can use this in the meantime by installing the development version of `wom.py`

```bash
pip install -U git+https://github.com/Jonxslays/wom.py
```

Example Usage

```py
from wom import Bosses, Skills

random_boss = Bosses.at_random()
random_skill = Skills.at_random()
# ... etc
```
